server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hnd_db
    username: root
    password: mysqldevpassword
  jpa:
    generate-ddl: true
  liquibase:
    enabled: false
  security:
    user:
      name: HnD_Creator
      password: password

env:
  jwt-secret-key: ${{ secrets.JWT_SECRET_KEY }}