server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hnd_db
    username: root
    password: mysqldevpassword
  jpa:
    generate-ddl: true
  liquibase:
    enabled: false
